name: anchore-analysis

env:
  DOCKER_IMAGE_NAME: sequeljs/devcontainer

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - main

jobs:
  anchore-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          load: true
          push: false
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Perform Anchore analysis
        uses: anchore/scan-action@v3
        with:
          acs-report-enable: true
          fail-build: false
          image: ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Upload Anchore report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
